FROM python:3.9.23-alpine3.22  
 
RUN mkdir /app
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 
 
RUN pip install --upgrade pip 
COPY server/ /app/
RUN pip freeze > requirements.txt /app/
 
RUN pip install --no-cache-dir -r requirements.txt
 
 
EXPOSE 8000

RUN python auth/manage.py makemigrations
RUN python auth/manage.py migrate

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]